-- ============================================================
-- Cigarette stock count — Supabase schema
-- Run this before 02_seed.sql.
--
-- Design notes:
--  * product_id IS the POS Item ID. It is the join key everywhere.
--    PLU is display-only: it is shown to staff so they can check the
--    pack, and it is NOT used to join, because the POS export contains
--    the same PLU with and without a leading zero on some lines.
--  * Counts key on product, never on shelf position. Moving a product
--    on the shelf therefore cannot break historical data.
--  * Counts are in PACKS. Cartons are out of scope.
-- ============================================================

-- ---------- reference data ----------

create table if not exists branch (
  branch_id   text primary key,
  name        text not null,
  pos_site_id text
);

create table if not exists product (
  product_id      text primary key,          -- POS Item ID, e.g. '103732'
  plu             text not null,             -- shown to staff, not a join key
  pos_description text not null,             -- exact wording from the POS
  short_name      text not null,             -- what appears on the count block
  brand           text,
  active          boolean not null default true
);

-- Names as written in the planogram spreadsheet. Lets the importer resolve
-- a grid cell to a product even when the spreadsheet uses an older label.
create table if not exists product_alias (
  alias      text primary key,
  product_id text not null references product(product_id)
);

-- ---------- planogram ----------

create table if not exists planogram_version (
  version_id     bigint generated by default as identity primary key,
  branch_id      text not null references branch(branch_id),
  effective_from date not null default current_date,
  status         text not null default 'draft'
                 check (status in ('draft','active','archived')),
  note           text,
  created_at     timestamptz not null default now()
);

-- At most one active planogram per branch.
create unique index if not exists planogram_version_one_active
  on planogram_version (branch_id) where status = 'active';

create table if not exists planogram_facing (
  version_id bigint not null references planogram_version(version_id) on delete cascade,
  shelf      text not null check (shelf ~ '^[A-Z]$'),
  position   integer not null check (position between 1 and 99),
  product_id text not null references product(product_id),
  primary key (version_id, shelf, position)
);

create index if not exists planogram_facing_product
  on planogram_facing (version_id, product_id);

-- ---------- counts ----------

create table if not exists stock_count (
  count_id     bigint generated by default as identity primary key,
  branch_id    text not null references branch(branch_id),
  version_id   bigint not null references planogram_version(version_id),
  count_date   date not null,
  shift        text not null check (shift in ('DAY','NIGHT')),
  staff_name   text not null,
  status       text not null default 'draft' check (status in ('draft','submitted')),
  started_at   timestamptz not null default now(),
  submitted_at timestamptz,
  unique (branch_id, count_date, shift)
);

create table if not exists stock_count_line (
  count_id     bigint not null references stock_count(count_id) on delete cascade,
  product_id   text not null references product(product_id),
  packs        integer check (packs >= 0),
  add_in       integer not null default 0 check (add_in >= 0),
  not_on_shelf boolean not null default false,
  primary key (count_id, product_id),
  -- a line is either counted or explicitly marked absent, never blank
  constraint counted_or_absent check (not_on_shelf or packs is not null)
);

-- ---------- sales, imported from the POS ----------

create table if not exists pos_sales_daily (
  branch_id  text not null references branch(branch_id),
  sale_date  date not null,
  product_id text not null references product(product_id),
  qty_sold   integer not null,
  primary key (branch_id, sale_date, product_id)
);

-- ---------- reconciliation ----------

create or replace view vw_count_submitted as
  select sc.branch_id, sc.count_date, sc.shift, sc.staff_name,
         l.product_id, l.packs, l.add_in, l.not_on_shelf
  from stock_count sc
  join stock_count_line l on l.count_id = sc.count_id
  where sc.status = 'submitted';

-- Sold (physical) = opening + add-in - closing.
-- Opening is the previous submitted count's closing for the same product.
create or replace view vw_daily_reconciliation as
  select
    f.branch_id,
    f.count_date,
    f.shift,
    f.staff_name,
    p.product_id,
    p.plu,
    p.short_name,
    p.pos_description,
    lag(f.packs) over w                      as opening_packs,
    f.add_in,
    coalesce(f.packs, 0)                     as closing_packs,
    (lag(f.packs) over w) + f.add_in
      - coalesce(f.packs, 0)                 as sold_physical,
    s.qty_sold                               as sold_pos,
    ((lag(f.packs) over w) + f.add_in
      - coalesce(f.packs, 0)) - s.qty_sold   as variance_packs
  from vw_count_submitted f
  join product p on p.product_id = f.product_id
  left join pos_sales_daily s
    on s.branch_id = f.branch_id
   and s.sale_date = f.count_date
   and s.product_id = f.product_id
  window w as (partition by f.branch_id, f.product_id order by f.count_date);

-- ---------- row level security ----------
-- Staff reach Supabase with the anon key through PetronTasks, so the rules
-- live here rather than in the client.

alter table branch            enable row level security;
alter table product           enable row level security;
alter table product_alias     enable row level security;
alter table planogram_version enable row level security;
alter table planogram_facing  enable row level security;
alter table stock_count       enable row level security;
alter table stock_count_line  enable row level security;
alter table pos_sales_daily   enable row level security;

-- Reference data: readable by the app, writable only with the service key.
create policy read_branch    on branch            for select to anon using (true);
create policy read_product   on product           for select to anon using (true);
create policy read_alias     on product_alias     for select to anon using (true);
create policy read_version   on planogram_version for select to anon using (status = 'active');
create policy read_facing    on planogram_facing  for select to anon using (true);

-- Counts: staff may create and edit their own count while it is a draft.
-- Once submitted it is frozen — no update, and no delete for anyone.
create policy insert_count on stock_count for insert to anon with check (status = 'draft');
create policy read_count   on stock_count for select to anon using (true);
create policy update_count on stock_count for update to anon
  using (status = 'draft');

create policy insert_line on stock_count_line for insert to anon with check (
  exists (select 1 from stock_count c
          where c.count_id = stock_count_line.count_id and c.status = 'draft'));
create policy read_line   on stock_count_line for select to anon using (true);
create policy update_line on stock_count_line for update to anon using (
  exists (select 1 from stock_count c
          where c.count_id = stock_count_line.count_id and c.status = 'draft'));

-- Sales data is loaded with the service key and read by reporting only.
create policy read_sales on pos_sales_daily for select to anon using (true);
