-- ============================================================
-- 04 — sync the database to CIGARETTES PLANOGRAM.xlsx
--
-- Generated by diff_xlsx_vs_db.py. Run AFTER 01/02/03.
-- The database had drifted from the spreadsheet: LD 100 Red was
-- absent entirely and its two facings had been absorbed into the
-- LD Red block, making C21-25 one contiguous product.
--
-- Idempotent.
-- ============================================================

begin;

-- Products present in the spreadsheet but missing from the database.
insert into product (product_id, plu, pos_description, short_name, brand) values
  ('107628', '9555900301227', 'LD 100 RED', 'LD 100 Red', 'LD')
on conflict (product_id) do update set
  plu = excluded.plu, pos_description = excluded.pos_description;

-- Grid labels that the importer cannot currently resolve.
insert into product_alias (alias, product_id) values
  ('LD 100 RED', '107628')
on conflict (alias) do update set product_id = excluded.product_id;

-- 2 facing(s) that disagree with the grid.
insert into planogram_facing (version_id, shelf, position, product_id) values
  (1, 'C', 22, '107628'),
  (1, 'C', 24, '107628')
on conflict (version_id, shelf, position) do update set
  product_id = excluded.product_id;

-- Aliases the current grid no longer uses. Left in place on purpose:
-- they still resolve to the right product, so an older copy of the
-- spreadsheet keeps importing. Uncomment only if you want them gone.
-- delete from product_alias where alias = 'RED Winston';

commit;

-- Expected afterwards: 54 products, 162 facings, 58 blocks,
-- 3 products split across blocks (LD Red, LD 100 Red, Marlboro Black).
