-- ============================================================
-- 11 — restocks: packs put ONTO the shelf, recorded as they happen
--
-- Run AFTER 10_prices_and_opening_date.sql, in the Supabase SQL editor.
-- Independent of 09 (which is optional and not applied).
--
-- ------------------------------------------------------------
-- WHY A SEPARATE TABLE AND NOT stock_count_line.add_in
-- ------------------------------------------------------------
-- add_in already exists on the count line, so the obvious move is to write
-- there. It cannot work, for four separate reasons:
--
--   * a restock happens at 3pm; that trading day's count row does not exist
--     yet and will not until after midnight
--   * once a count is submitted RLS freezes it, so an evening delivery after
--     the previous night's count was closed has nowhere to go
--   * the count screen's submit upserts every line with add_in = 0, which
--     would silently wipe anything written there earlier in the day
--   * several deliveries a day is normal, and one column cannot accumulate
--     without a read-modify-write race
--
-- So a restock is its own event, with its own record of who and when, and
-- reconciliation sums them. The count screen keeps its single input and its
-- blindness; nothing about it changes.
--
-- ------------------------------------------------------------
-- WHY RESTOCKS ATTACH TO THE COUNT PERIOD, NOT THE CALENDAR DAY
-- ------------------------------------------------------------
-- opening_packs is the previous SUBMITTED count's closing, taken on
-- opening_date — which is not always yesterday. Skip a night and one count
-- spans two days of selling.
--
-- If restocks were matched on restock_date = count_date, the skipped day's
-- delivery would be dropped on the floor: its packs went onto the shelf and
-- sold down inside the period being reconciled, but nothing would add them
-- back. The variance would read as shrinkage of exactly the delivery size.
--
-- Matching the whole period instead — (opening_date, count_date] — keeps
-- add-in and sold-down over the same span, whatever that span turns out to be.
-- ============================================================

begin;

-- ---------- tables ----------

create table if not exists stock_restock (
  restock_id   bigint generated by default as identity primary key,
  branch_id    text not null references branch(branch_id),
  restock_date date not null,
  staff_name   text not null,
  note         text,
  status       text not null default 'draft'
               check (status in ('draft','submitted','void')),
  void_reason  text,
  created_at   timestamptz not null default now(),
  submitted_at timestamptz,
  voided_at    timestamptz
);

-- Deliberately NO unique constraint on (branch_id, restock_date). One count
-- per branch per trading day is the rule for counts; several restocks a day
-- is the normal case here, and is the whole point of the feature.

create index if not exists stock_restock_lookup
  on stock_restock (branch_id, restock_date) where status = 'submitted';

create table if not exists stock_restock_line (
  restock_id bigint not null references stock_restock(restock_id) on delete cascade,
  product_id text not null references product(product_id),
  packs      integer not null check (packs > 0),
  primary key (restock_id, product_id)
);

comment on column stock_restock.restock_date is
  'The trading day the packs went onto the shelf, NOT the clock date. Same 7am '
  'MYT rollover as stock_count.count_date, so a delivery entered at 1am belongs '
  'to the day that is closing. Defaulted in the page and editable there; never '
  'derived from now() at write time.';

comment on column stock_restock.staff_name is
  'Who was at the keyboard. A margin note, not authentication — the restock '
  'page has no sign-in, exactly like the sales import page.';

comment on column stock_restock_line.packs is
  'Packs ADDED to the shelf. Always positive: a restock of zero is not a '
  'restock, and products that were not restocked simply have no row. There is '
  'no negative adjustment — a mistake is corrected by voiding and re-entering.';

-- ---------- status transitions ----------
-- A trigger, not RLS. Multiple permissive UPDATE policies OR their USING and
-- their WITH CHECK clauses together, so a "submit" policy and a "void" policy
-- side by side would between them permit submitted -> draft and unfreeze a
-- record neither policy meant to allow. A trigger sees OLD and NEW and can say
-- exactly what it means.
--
-- Same family of bug as 05_fix_submit_policy.sql: what a policy permits is not
-- always what it looks like it permits.

create or replace function stock_restock_transition() returns trigger
language plpgsql as $$
begin
  if old.status = new.status then
    -- Editing a draft is fine. A submitted or void row is frozen: its own
    -- columns must not move either.
    if old.status <> 'draft'
       and (new.restock_date, new.staff_name, new.note)
        is distinct from (old.restock_date, old.staff_name, old.note) then
      raise exception 'restock % is % and frozen', old.restock_id, old.status
        using errcode = 'check_violation';
    end if;
    return new;
  end if;

  if old.status = 'draft' and new.status = 'submitted' then
    new.submitted_at := coalesce(new.submitted_at, now());
    return new;
  end if;

  if old.status = 'submitted' and new.status = 'void' then
    if coalesce(btrim(new.void_reason), '') = '' then
      raise exception 'voiding a restock needs a reason'
        using errcode = 'check_violation';
    end if;
    new.voided_at := coalesce(new.voided_at, now());
    return new;
  end if;

  raise exception 'restock status cannot go from % to %', old.status, new.status
    using errcode = 'check_violation';
end $$;

drop trigger if exists stock_restock_transition_trg on stock_restock;
create trigger stock_restock_transition_trg
  before update on stock_restock
  for each row execute function stock_restock_transition();

-- Lines follow the parent: writable only while it is a draft.
--
-- NEW is unassigned on DELETE in PL/pgSQL and reading a field off it raises
-- 'record "new" is not assigned yet', so the branch on TG_OP is not tidiness.
create or replace function stock_restock_line_frozen() returns trigger
language plpgsql as $$
declare
  rid bigint;
  st  text;
begin
  if tg_op = 'DELETE' then rid := old.restock_id; else rid := new.restock_id; end if;

  select status into st from stock_restock where restock_id = rid;
  if st is distinct from 'draft' then
    raise exception 'restock % is % — its lines are frozen', rid, st
      using errcode = 'check_violation';
  end if;

  if tg_op = 'DELETE' then return old; else return new; end if;
end $$;

drop trigger if exists stock_restock_line_frozen_trg on stock_restock_line;
create trigger stock_restock_line_frozen_trg
  before insert or update or delete on stock_restock_line
  for each row execute function stock_restock_line_frozen();

-- ---------- row level security ----------
-- Mirrors the count tables. No delete policy on stock_restock itself: a wrong
-- restock is voided, which keeps the record and takes it out of reconciliation.
-- Draft LINES may be deleted — see the note further down for why.

alter table stock_restock      enable row level security;
alter table stock_restock_line enable row level security;

drop policy if exists read_restock   on stock_restock;
drop policy if exists insert_restock on stock_restock;
drop policy if exists update_restock on stock_restock;

create policy read_restock   on stock_restock for select to anon using (true);
create policy insert_restock on stock_restock for insert to anon
  with check (status = 'draft');
-- The trigger decides which transitions are legal; the policy only has to let
-- the update reach it. Stating both clauses explicitly because Postgres reuses
-- USING as WITH CHECK when none is given — the 05 lesson.
create policy update_restock on stock_restock for update to anon
  using (status in ('draft','submitted'))
  with check (status in ('draft','submitted','void'));

drop policy if exists read_restock_line   on stock_restock_line;
drop policy if exists insert_restock_line on stock_restock_line;
drop policy if exists update_restock_line on stock_restock_line;

create policy read_restock_line on stock_restock_line for select to anon using (true);
create policy insert_restock_line on stock_restock_line for insert to anon with check (
  exists (select 1 from stock_restock r
           where r.restock_id = stock_restock_line.restock_id and r.status = 'draft'));
create policy update_restock_line on stock_restock_line for update to anon using (
  exists (select 1 from stock_restock r
           where r.restock_id = stock_restock_line.restock_id and r.status = 'draft'));
-- Lines of a DRAFT may be deleted. This is the one delete path in the module
-- and it is deliberate: the page writes its lines and then flips the parent to
-- submitted, so a failed attempt can leave lines for products the user has
-- since removed. A draft is in no view and reconciles nothing, so clearing them
-- on retry costs nothing. The moment the parent is submitted the trigger above
-- refuses, and there is no delete policy on stock_restock itself.
drop policy if exists delete_restock_line on stock_restock_line;
create policy delete_restock_line on stock_restock_line for delete to anon using (
  exists (select 1 from stock_restock r
           where r.restock_id = stock_restock_line.restock_id and r.status = 'draft'));

-- ---------- what the pages read ----------

create or replace view vw_restock_daily as
  select r.branch_id,
         r.restock_date,
         l.product_id,
         sum(l.packs)::int as packs
    from stock_restock r
    join stock_restock_line l on l.restock_id = r.restock_id
   where r.status = 'submitted'
   group by r.branch_id, r.restock_date, l.product_id;

comment on view vw_restock_daily is
  'Submitted restocks summed per branch, trading day and product. Draft and '
  'void restocks are excluded, which is what makes voiding a correction.';

-- ---------- reconciliation ----------
-- COLUMN NAMES, ORDER AND TYPES ARE UNCHANGED. create or replace view requires
-- it, excel/counts_query.m pins this exact list as Expected, and
-- excel/build_workbook.py addresses the Data sheet by column position. The only
-- change is what add_in contains.
--
-- The window functions move into a CTE so the lateral below can test each row
-- against its own opening_date.

create or replace view vw_daily_reconciliation as
  with base as (
    select f.branch_id, f.count_date, f.shift, f.staff_name, f.product_id,
           f.packs, f.add_in,
           lag(coalesce(f.packs, 0)) over w as opening_packs,
           lag(f.count_date)         over w as opening_date
      from vw_count_submitted f
    window w as (partition by f.branch_id, f.product_id order by f.count_date)
  )
  select
    b.branch_id,
    b.count_date,
    b.shift,
    b.staff_name,
    p.product_id,
    p.plu,
    p.short_name,
    p.pos_description,
    b.opening_packs,
    b.add_in + coalesce(r.added, 0)                     as add_in,
    coalesce(b.packs, 0)                                as closing_packs,
    b.opening_packs + b.add_in + coalesce(r.added, 0)
      - coalesce(b.packs, 0)                            as sold_physical,
    s.qty_sold                                          as sold_pos,
    (b.opening_packs + b.add_in + coalesce(r.added, 0)
      - coalesce(b.packs, 0)) - s.qty_sold              as variance_packs,
    b.opening_date,
    coalesce(s.unit_price, p.unit_price)                as unit_price_used,
    round(
      ((b.opening_packs + b.add_in + coalesce(r.added, 0)
        - coalesce(b.packs, 0)) - s.qty_sold)
      * coalesce(s.unit_price, p.unit_price), 2)        as variance_rm
  from base b
  join product p on p.product_id = b.product_id
  left join pos_sales_daily s
    on s.branch_id  = b.branch_id
   and s.sale_date  = b.count_date
   and s.product_id = b.product_id
  left join lateral (
    select sum(v.packs)::int as added
      from vw_restock_daily v
     where v.branch_id  = b.branch_id
       and v.product_id = b.product_id
       and v.restock_date <= b.count_date
       -- (opening_date, count_date]. On a product's first ever count there is
       -- no opening to sell down from, so sold_physical is null whatever this
       -- returns; same-day restocks are shown rather than hidden.
       and (case when b.opening_date is null
                 then v.restock_date = b.count_date
                 else v.restock_date > b.opening_date end)
  ) r on true;

comment on view vw_daily_reconciliation is
  'Sold (physical) = opening + add_in - closing, opening being the previous '
  'submitted count''s closing for the same product, taken on opening_date. '
  'add_in is the count line''s own add_in (always 0 since the count screen was '
  'cut to one input) plus every SUBMITTED restock in the period '
  '(opening_date, count_date] — the period, not the calendar day, so a skipped '
  'count does not drop that day''s delivery. A not_on_shelf line stores packs = '
  'null and is read as zero on BOTH sides. opening_packs and opening_date are '
  'both null on a product''s first ever count. variance_rm values the variance '
  'at the price that day''s report printed, falling back to the product list '
  'price, and is null when neither is known.';

commit;

-- ============================================================
-- Verification. Read-only apart from a restock it rolls back.
-- ============================================================

-- 1. The view's shape must not have moved. Expect exactly these 17 names in
--    this order — counts_query.m and build_workbook.py both depend on it.
select string_agg(column_name, ',' order by ordinal_position) as actual,
       string_agg(column_name, ',' order by ordinal_position) =
         'branch_id,count_date,shift,staff_name,product_id,plu,short_name,'
         'pos_description,opening_packs,add_in,closing_packs,sold_physical,'
         'sold_pos,variance_packs,opening_date,unit_price_used,variance_rm'
         as unchanged
  from information_schema.columns
 where table_name = 'vw_daily_reconciliation';

-- 2. The trigger must refuse to unfreeze. Each of these should RAISE; run them
--    one at a time and read the error.
--    begin;
--      insert into stock_restock (branch_id, restock_date, staff_name)
--           values ('SAFARI', current_date, 'trigger probe') returning restock_id;
--      -- draft -> void is not a legal jump:
--      update stock_restock set status = 'void', void_reason = 'x'
--       where staff_name = 'trigger probe';                      -- expect ERROR
--      update stock_restock set status = 'submitted'
--       where staff_name = 'trigger probe';                      -- expect OK
--      -- submitted -> draft must not reopen a frozen record:
--      update stock_restock set status = 'draft'
--       where staff_name = 'trigger probe';                      -- expect ERROR
--      -- a void needs a reason:
--      update stock_restock set status = 'void'
--       where staff_name = 'trigger probe';                      -- expect ERROR
--      update stock_restock set status = 'void', void_reason = 'probe'
--       where staff_name = 'trigger probe';                      -- expect OK
--      -- void is terminal:
--      update stock_restock set status = 'submitted'
--       where staff_name = 'trigger probe';                      -- expect ERROR
--    rollback;

-- 3. A restock must move add_in on exactly the rows it should, and nothing
--    else. Run the whole block; it rolls back.
--    begin;
--      create temp table before_ as
--        select count_date, product_id, add_in, sold_physical
--          from vw_daily_reconciliation where branch_id = 'SAFARI';
--
--      with r as (
--        insert into stock_restock (branch_id, restock_date, staff_name, status)
--        values ('SAFARI', date '2026-09-11', 'reconciliation probe', 'draft')
--        returning restock_id)
--      insert into stock_restock_line (restock_id, product_id, packs)
--      select restock_id, '100740', 7 from r;
--
--      update stock_restock set status = 'submitted'
--       where staff_name = 'reconciliation probe';
--
--      -- Expect ONE row: product 100740 on 2026-09-11, add_in 0 -> 7 and
--      -- sold_physical up by 7. Any other row means the period test is wrong.
--      select a.count_date, a.product_id,
--             b.add_in as was, a.add_in as now_,
--             b.sold_physical as was_sold, a.sold_physical as now_sold
--        from vw_daily_reconciliation a
--        join before_ b using (count_date, product_id)
--       where a.branch_id = 'SAFARI'
--         and (a.add_in, a.sold_physical) is distinct from (b.add_in, b.sold_physical);
--    rollback;
