-- ============================================================
-- 16 — seed the lubes and Iluma shelves
--
-- GENERATED by gen_seed_from_xlsx.py from excel/Lubes planogram.xlsx.
-- Do not hand-edit: re-run the generator instead, which is also how the
-- three products still missing a POS Item ID get added once they have one.
--
-- Run AFTER 15_categories.sql. Idempotent.
-- ============================================================

begin;

-- ---------- LUBES ----------
insert into product (product_id, plu, pos_description, short_name, brand, active, category) values
  ('103276', '4806505973308', 'PETRON ATF PREMIUM HTP 1L (WM)', 'ATF PREMIUM HTP 1L', 'ATF', true, 'LUBES'),
  ('103281', '9555671000367', 'PETRON BRAKE&CLUTCH FLUID DOT3 500ML', 'BRAKE & CLUTCH DOT3 500ML', 'Brake & Clutch', true, 'LUBES'),
  ('103584', '9555671000633', 'PETRON REV X PREMIUM MULTIGRADE API CI-4', 'REV-X PREMIUM 15W40 1L', 'REV-X', true, 'LUBES'),
  ('103586', '9555671000640', 'REV X MULTIGRADE API CF/SF SAE 15W-40 1L', 'REV-X MULTI 15W40 1L', 'REV-X', true, 'LUBES'),
  ('103591', '9555671000404', 'PETRON BLAZE RACING SYNTHETIC BLEND 10W40', 'BLAZE SYN 10W40 1L (OLD)', 'Blaze', false, 'LUBES'),
  ('104312', '9555671000398', 'PETRON BLAZE RACING HTP 0W40 4L (WM)', 'BLAZE HTP 0W40 4L', 'Blaze', true, 'LUBES'),
  ('104315', '9555671000459', 'PETRON BLAZE RACING PREMIUM MULTIGRADE 10W30 4L', 'BLAZE PREMIUM 10W30 4L', 'Blaze', true, 'LUBES'),
  ('104322', '9555671000619', 'PETRON BRAKE&CLUTCH FLUID DOT4 500ML', 'BRAKE & CLUTCH DOT4 500ML', 'Brake & Clutch', true, 'LUBES'),
  ('104323', '9555671000695', 'PETRON BLAZE RACING MULTIGRADE 20W50 4L', 'BLAZE MULTI 20W50 4L', 'Blaze', true, 'LUBES'),
  ('104325', '9555671000718', 'PETRON REV-X PREMIUM MULTIGRADE 15W40 4L', 'REV-X PREMIUM 15W40 4L', 'REV-X', true, 'LUBES'),
  ('104446', '4806505972806', 'PETRON RIDER 4T FULLY SYNTHETIC 10W40 1L', 'RIDER 4T FULL SYN 10W40 1L', 'Rider', false, 'LUBES'),
  ('104504', '9555671000732', 'PETRON RIDER 4T MONOGRADE SAE 40 API SG', 'RIDER 4T MONOGRADE SAE40 1L', 'Rider', true, 'LUBES'),
  ('104651', '9555671000831', 'PETRON RIDER 4T MULTIGRADE 20W40 API SJ', 'RIDER 4T MULTI 20W40 1L', 'Rider', true, 'LUBES'),
  ('105600', '4806505973971', 'PETRON 2T AUTOLUBE JASO FB 1L', '2T AUTOLUBE 1L', '2T', true, 'LUBES'),
  ('105601', '4806505973988', 'PETRON 2T POWERBURN JASO FB 1L', '2T POWERBURN 1L', '2T', true, 'LUBES'),
  ('105602', '4806505973995', 'PETRON 2T PREMIUM API TC/JASO FB 1L', '2T PREMIUM 1L', '2T', true, 'LUBES'),
  ('105603', '4806505974053', 'PETRON BLAZE RACING FULLY SYNTHETIC 5W40', 'BLAZE FULLY SYN 5W40 1L', 'Blaze', true, 'LUBES'),
  ('105604', '4806505974060', 'PETRON REV X MONOGRADE SAE 40 API CF/SF', 'REV-X MONOGRADE SAE40 1L', 'REV-X', true, 'LUBES'),
  ('105610', '4806505974138', 'PETRON RIDER 4T PREMIUM MULTIGRADE 15W40', 'RIDER 4T PREMIUM 15W40 1L', 'Rider', true, 'LUBES'),
  ('105613', '4806505974183', 'PETRON BLAZE RACING PREMIUM MULTIGRADE 15W40 4L', 'BLAZE PREMIUM 15W40 4L', 'Blaze', true, 'LUBES'),
  ('105615', '4806505974206', 'PETRON BLAZE RACING SYNTHETIC BLEND 10W40 4L', 'BLAZE SYN 10W40 4L', 'Blaze', true, 'LUBES'),
  ('105616', '4806505974213', 'PETRON BLAZE RACING FULLY SYNTHETIC 5W40', 'BLAZE FULLY SYN 5W40 4L', 'Blaze', true, 'LUBES'),
  ('105622', '4806505974282', 'PETRON BLAZE RACING PREMIUM MULTIGRADE 10W30', 'BLAZE PREMIUM 10W30 1L', 'Blaze', true, 'LUBES'),
  ('105623', '4806505974299', 'PETRON BLAZE RACING PREMIUM MULTIGRADE 15W40', 'BLAZE PREMIUM 15W40 1L', 'Blaze', true, 'LUBES'),
  ('105625', '4806505974312', 'PETRON BLAZE RACING SYNTHETIC BLEND 10W40', 'BLAZE SYN 10W40 1L', 'Blaze', true, 'LUBES'),
  ('105626', '4806505974329', 'PETRON BLAZE RACING SYNTHETIC BLEND 5W30', 'BLAZE SYN 5W30 1L', 'Blaze', false, 'LUBES'),
  ('105627', '4806505974343', 'PETRON RIDER 4T SYNTHETIC BLEND 10W40', 'RIDER 4T SYN BLEND 10W40 1L', 'Rider', true, 'LUBES'),
  ('105629', '4806505974367', 'PETRON BLAZE RACING SYNTHETIC BLEND 5W30 4L', 'BLAZE SYN 5W30 4L', 'Blaze', true, 'LUBES'),
  ('105632', '4806505974398', 'PETRON REV-X TURBO HTP 5W40 APICJ-4 4L', 'REV-X TURBO HTP 5W40 4L', 'REV-X', true, 'LUBES'),
  ('105633', '4806505974404', 'PETRON BLAZE RACING FULLY SYNTHETIC 0W20', 'BLAZE FULLY SYN 0W20 4L', 'Blaze', true, 'LUBES'),
  ('106517', '4806505973483', 'PETRON RIDER 4T SCOOTER OIL PREMIUM', 'RIDER 4T SCOOTER 1L', 'Rider', true, 'LUBES'),
  ('107716', '9555671000909', 'PETRON BLAZE RACING MULTIGRADE 20W50', 'BLAZE MULTI 20W50 1L', 'Blaze', true, 'LUBES'),
  ('107811', '9555671001043', 'PETRON BLAZE RACING FULLY SYNTHETIC API SP', 'BLAZE FULLY SYN 5W30 4L', 'Blaze', true, 'LUBES'),
  ('108194', '4806505974732', 'PETRON SUPER COOLANT 0.5L (PREMIX)', 'SUPER COOLANT 500ML', 'Coolant', true, 'LUBES')
on conflict (product_id) do update set
  plu = excluded.plu, pos_description = excluded.pos_description,
  short_name = excluded.short_name, brand = excluded.brand,
  active = excluded.active, category = excluded.category;

insert into product_alias (alias, product_id) values
  ('2T AUTOLUBE 1L', '105600'),
  ('2T POWERBURN 1L', '105601'),
  ('2T PREMIUM 1L', '105602'),
  ('ATF PREMIUM HTP 1L', '103276'),
  ('BLAZE FULLY SYN 0W20 4L', '105633'),
  ('BLAZE FULLY SYN 5W30 4L', '107811'),
  ('BLAZE FULLY SYN 5W40 1L', '105603'),
  ('BLAZE FULLY SYN 5W40 4L', '105616'),
  ('BLAZE HTP 0W40 4L', '104312'),
  ('BLAZE MULTI 20W50 1L', '107716'),
  ('BLAZE MULTI 20W50 4L', '104323'),
  ('BLAZE PREMIUM 10W30 1L', '105622'),
  ('BLAZE PREMIUM 10W30 4L', '104315'),
  ('BLAZE PREMIUM 15W40 1L', '105623'),
  ('BLAZE PREMIUM 15W40 4L', '105613'),
  ('BLAZE SYN 10W40 1L', '105625'),
  ('BLAZE SYN 10W40 4L', '105615'),
  ('BLAZE SYN 5W30 4L', '105629'),
  ('BRAKE & CLUTCH DOT3 500ML', '103281'),
  ('BRAKE & CLUTCH DOT4 500ML', '104322'),
  ('REV-X MONOGRADE SAE40 1L', '105604'),
  ('REV-X MULTI 15W40 1L', '103586'),
  ('REV-X PREMIUM 15W40 1L', '103584'),
  ('REV-X PREMIUM 15W40 4L', '104325'),
  ('REV-X TURBO HTP 5W40 4L', '105632'),
  ('RIDER 4T MONOGRADE SAE40 1L', '104504'),
  ('RIDER 4T MULTI 20W40 1L', '104651'),
  ('RIDER 4T PREMIUM 15W40 1L', '105610'),
  ('RIDER 4T SCOOTER 1L', '106517'),
  ('RIDER 4T SYN BLEND 10W40 1L', '105627'),
  ('SUPER COOLANT 500ML', '108194')
on conflict (alias) do update set product_id = excluded.product_id;

insert into planogram_version (branch_id, category, status, effective_from, note)
select 'SAFARI', 'LUBES', 'active', current_date,
       'Seeded from Lubes planogram.xlsx'
 where not exists (select 1 from planogram_version
                    where branch_id = 'SAFARI' and category = 'LUBES'
                      and status = 'active');

insert into planogram_facing (version_id, shelf, position, product_id)
select v.version_id, f.shelf, f.position, f.product_id
  from (values
    ('A', 1, '105627'),
    ('A', 2, '105627'),
    ('A', 3, '105610'),
    ('A', 4, '105610'),
    ('A', 5, '104651'),
    ('A', 6, '104504'),
    ('A', 7, '105602'),
    ('A', 8, '105600'),
    ('A', 9, '105601'),
    ('A', 10, '106517'),
    ('A', 11, '103276'),
    ('A', 12, '104322'),
    ('A', 13, '103281'),
    ('A', 14, '108194'),
    ('A', 15, '105603'),
    ('A', 16, '105603'),
    ('A', 17, '105625'),
    ('B', 2, '105622'),
    ('B', 3, '105622'),
    ('B', 4, '105623'),
    ('B', 5, '105623'),
    ('B', 6, '105623'),
    ('B', 7, '107716'),
    ('B', 8, '107716'),
    ('B', 11, '103584'),
    ('B', 12, '103584'),
    ('B', 13, '103586'),
    ('B', 14, '103586'),
    ('B', 15, '103586'),
    ('B', 16, '103586'),
    ('B', 17, '105604'),
    ('C', 1, '104312'),
    ('C', 2, '105616'),
    ('C', 3, '105633'),
    ('C', 4, '107811'),
    ('C', 5, '104315'),
    ('C', 6, '105613'),
    ('C', 7, '104323'),
    ('C', 8, '104323'),
    ('D', 1, '105632'),
    ('D', 2, '104325'),
    ('D', 3, '105615'),
    ('D', 4, '105616'),
    ('D', 5, '105629'),
    ('D', 6, '104315'),
    ('D', 7, '105613'),
    ('D', 8, '104323')
  ) as f(shelf, position, product_id)
  cross join (select version_id from planogram_version
               where branch_id = 'SAFARI' and category = 'LUBES'
                 and status = 'active') v
on conflict (version_id, shelf, position) do update set
  product_id = excluded.product_id;

-- ---------- ILUMA ----------
insert into product (product_id, plu, pos_description, short_name, brand, active, category) values
  ('105740', '7622100698326', 'FIIT ALPINE', 'FIIT ALPINE', 'FIIT', true, 'ILUMA'),
  ('105741', '7622100698388', 'FIIT REGULAR', 'FIIT REGULAR', 'FIIT', true, 'ILUMA'),
  ('105742', '7622100698418', 'FIIT CRISP', 'FIIT CRISP', 'FIIT', true, 'ILUMA'),
  ('107075', '9555277310570', 'TEREA RUSSSET', 'TEREA RUSSET', 'TEREA', true, 'ILUMA'),
  ('107088', '7622100699521', 'TEREA BLACK GREEN', 'TEREA BLACK GREEN', 'TEREA', true, 'ILUMA'),
  ('107089', '9555277316510', 'TEREA AMBER', 'TEREA AMBER', 'TEREA', true, 'ILUMA'),
  ('107090', '9555277316572', 'TEREA TURQUOISE', 'TEREA TURQUOISE', 'TEREA', true, 'ILUMA'),
  ('107091', '9555277316602', 'TEREA SIENNA', 'TEREA SIENNA', 'TEREA', true, 'ILUMA'),
  ('107092', '9555277316633', 'TEREA LEMON', 'TEREA LEMON', 'TEREA', true, 'ILUMA'),
  ('107093', '9555277316664', 'TEREA BLUEBERRY', 'TEREA BLUEBERRY', 'TEREA', true, 'ILUMA'),
  ('107094', '9555277316695', 'TEREA BLUE', 'TEREA BLUE', 'TEREA', true, 'ILUMA'),
  ('107391', '7622100701019', 'TEREA WATERMELON CAPSULE', 'TEREA WATERMELON', 'TEREA', true, 'ILUMA'),
  ('107392', '7622100701064', 'TEREA PASSION FRUIT CAPSULE', 'TEREA PASSION FRUIT', 'TEREA', true, 'ILUMA'),
  ('107596', '7622100701620', 'TEREA BLACK YELLOW MNT S50 PRI 20 SLI', 'TEREA BLACK YELLOW', 'TEREA', true, 'ILUMA'),
  ('107597', '7622100701637', 'TEREA BLACKPU MNT S50 PRI 20 SLI', 'TEREA BLACK PURPLE', 'TEREA', true, 'ILUMA'),
  ('107775', '7622100702672', 'TEREA STRAWBERRY BASIL CAPSULE', 'TEREA STRAWBERRY BASIL', 'TEREA', true, 'ILUMA'),
  ('107776', '7622100702832', 'KIT IQOS ILUMA ONE MIDNIGHT BLACK KIT', 'ILUMA', 'IQOS', true, 'ILUMA'),
  ('108024', '7622100467199', 'TEREA KRETEK S50 PRI 20 SLI', 'TEREA KRETEK', 'TEREA', true, 'ILUMA'),
  ('108046', '7622100467229', 'TEREA KRETEK MULBERRY MNT S50 PRI 20 SLI', 'TEREA KRETEK MULBERRY', 'TEREA', true, 'ILUMA'),
  ('108284', '7622100467281', 'TEREA GRAPE CAPSULE S50 PRI 20 SLI', 'TEREA GRAPE', 'TEREA', true, 'ILUMA'),
  ('108285', '7622100467465', 'TEREA RRC MNT S50 PRI 20 SLI', 'TEREA RASPBERRY ROSE', 'TEREA', true, 'ILUMA')
on conflict (product_id) do update set
  plu = excluded.plu, pos_description = excluded.pos_description,
  short_name = excluded.short_name, brand = excluded.brand,
  active = excluded.active, category = excluded.category;

insert into product_alias (alias, product_id) values
  ('FIIT ALPINE', '105740'),
  ('FIIT CRISP', '105742'),
  ('FIIT REGULAR', '105741'),
  ('ILUMA', '107776'),
  ('TEREA AMBER', '107089'),
  ('TEREA BLACK GREEN', '107088'),
  ('TEREA BLACK PURPLE', '107597'),
  ('TEREA BLACK YELLOW', '107596'),
  ('TEREA BLUE', '107094'),
  ('TEREA BLUEBERRY', '107093'),
  ('TEREA GRAPE', '108284'),
  ('TEREA KRETEK', '108024'),
  ('TEREA KRETEK MULBERRY', '108046'),
  ('TEREA LEMON', '107092'),
  ('TEREA PASSION FRUIT', '107392'),
  ('TEREA RASPBERRY ROSE', '108285'),
  ('TEREA RUSSET', '107075'),
  ('TEREA SIENNA', '107091'),
  ('TEREA STRAWBERRY BASIL', '107775'),
  ('TEREA TURQUOISE', '107090'),
  ('TEREA WATERMELON', '107391')
on conflict (alias) do update set product_id = excluded.product_id;

insert into planogram_version (branch_id, category, status, effective_from, note)
select 'SAFARI', 'ILUMA', 'active', current_date,
       'Seeded from Lubes planogram.xlsx'
 where not exists (select 1 from planogram_version
                    where branch_id = 'SAFARI' and category = 'ILUMA'
                      and status = 'active');

insert into planogram_facing (version_id, shelf, position, product_id)
select v.version_id, f.shelf, f.position, f.product_id
  from (values
    ('A', 1, '107075'),
    ('A', 2, '107075'),
    ('A', 3, '107075'),
    ('B', 1, '107091'),
    ('B', 2, '107091'),
    ('B', 3, '107091'),
    ('C', 1, '107089'),
    ('C', 2, '107089'),
    ('C', 3, '107089'),
    ('D', 1, '107088'),
    ('D', 2, '107088'),
    ('D', 3, '107088'),
    ('E', 1, '107597'),
    ('E', 2, '107597'),
    ('E', 3, '107596'),
    ('F', 1, '107094'),
    ('F', 2, '107094'),
    ('F', 3, '107094'),
    ('G', 1, '107090'),
    ('G', 2, '107093'),
    ('G', 3, '107092'),
    ('H', 1, '107392'),
    ('H', 2, '107391'),
    ('H', 3, '107775'),
    ('I', 1, '108284'),
    ('I', 2, '108285'),
    ('I', 3, '108285'),
    ('J', 1, '108024'),
    ('J', 2, '108046'),
    ('J', 3, '108046'),
    ('K', 1, '105741'),
    ('K', 2, '105740'),
    ('K', 3, '105742'),
    ('L', 1, '107776')
  ) as f(shelf, position, product_id)
  cross join (select version_id from planogram_version
               where branch_id = 'SAFARI' and category = 'ILUMA'
                 and status = 'active') v
on conflict (version_id, shelf, position) do update set
  product_id = excluded.product_id;

commit;

-- ============================================================
-- Verify
-- ============================================================
-- LUBES: expect 31 products on the shelf, 47 facings, 3 seeded inactive (off the shelf)
-- ILUMA: expect 21 products on the shelf, 34 facings
select p.category, count(distinct p.product_id) filter (where p.active) as active_products,
       count(f.*) as facings
  from product p
  left join planogram_facing f on f.product_id = p.product_id
  left join planogram_version v on v.version_id = f.version_id and v.status = 'active'
 group by p.category order by p.category;

-- NOT SEEDED — these need a POS Item ID from the till before they can be
-- counted. Add them on the Edit the Shelf page; no migration needed.
--   row 18: 'BLAZE HTP 0W40 1L' has NO POS Item ID — left off the planogram (was at B1)
--   row 22: 'REV-X TURBO HTP 5W40 1L' has NO POS Item ID — left off the planogram (was at B9)
--   row 23: 'REV-X SYN BLEND 15W40' has NO POS Item ID — left off the planogram (was at B10)
--   LUBES: grid label 'BLAZE HTP 0W40 1L' at B1 matches no product
--   LUBES: grid label 'REV-X TURBO HTP 5W40 1L' at B9 matches no product
--   LUBES: grid label 'REV-X SYN BLEND 15W40' at B10 matches no product
