-- ============================================================
-- 18 — correcting a submitted count, without letting it happen quietly
--
-- Run in the Supabase SQL editor. Idempotent.
--
-- ------------------------------------------------------------
-- WHY THIS IS NOT SIMPLY "ALLOW UPDATE"
-- ------------------------------------------------------------
-- A submitted count is frozen by RLS on purpose: `vw_daily_reconciliation`
-- reads it, the Excel workbook reads that, and somebody has very likely already
-- printed the day. Changing a closing figure afterwards does not just fix one
-- number — it restates that day's variance AND the next day's opening, because
-- opening is the previous submitted count's closing.
--
-- That is still the right thing to allow. A miscount that cannot be fixed is a
-- permanent lie in the data, and the person who notices is standing at the
-- shelf. What must not happen is the fix being invisible: a figure that
-- disagrees with last week's printout needs a reason attached to it.
--
-- So the database, not the page, guarantees the audit trail:
--
--   * stock_count_line gains corrected_by / corrected_reason / corrected_at.
--   * A BEFORE UPDATE trigger REFUSES to change `packs` on a submitted count
--     unless both a name and a reason came with the same update.
--   * The same trigger writes the before-and-after into stock_count_correction
--     itself. The page cannot skip it, forget it, or fail halfway and leave the
--     change without its record.
--   * stock_count_correction has no update or delete policy, and anon cannot
--     insert into it at all — only the trigger can, through SECURITY DEFINER.
--     An audit row is permanent.
--
-- Decided 01 Oct 2026, with Rosa: anyone at the device may correct a count,
-- the way the count screen and the sales import already take a typed name. The
-- protection is the trail, not a gate.
--
-- ------------------------------------------------------------
-- THE 05 TRAP, AGAIN
-- ------------------------------------------------------------
-- Postgres reuses a policy's USING expression as its WITH CHECK when none is
-- given. 05_fix_submit_policy.sql is the bug that caused: a count could never
-- leave draft because the USING that selected drafts was also applied to the
-- new row. Every policy below states WITH CHECK explicitly.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1. Where the trail lives
-- ------------------------------------------------------------
create table if not exists stock_count_correction (
  correction_id bigint generated by default as identity primary key,
  count_id      bigint not null references stock_count(count_id) on delete cascade,
  product_id    text   not null references product(product_id),
  old_packs     integer,
  new_packs     integer not null check (new_packs >= 0),
  reason        text   not null check (length(btrim(reason)) >= 3),
  corrected_by  text   not null check (length(btrim(corrected_by)) >= 2),
  corrected_at  timestamptz not null default now()
);

create index if not exists stock_count_correction_count
  on stock_count_correction (count_id);

comment on table stock_count_correction is
  'Every change to a packs figure on a SUBMITTED count. Written by trigger, '
  'never by the application. No update or delete path exists.';

-- ------------------------------------------------------------
-- 2. Who and why, carried on the line itself
-- ------------------------------------------------------------
-- On the line as well as in the audit table, so the most recent reason travels
-- with the row every reader already fetches. All nullable: an ordinary count has
-- never been corrected and must not be made to look as though it has.
alter table stock_count_line add column if not exists corrected_by     text;
alter table stock_count_line add column if not exists corrected_reason text;
alter table stock_count_line add column if not exists corrected_at     timestamptz;

-- ------------------------------------------------------------
-- 3. The trigger that makes the trail unskippable
-- ------------------------------------------------------------
create or replace function stock_count_line_correct() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  parent_status text;
begin
  select status into parent_status from stock_count where count_id = new.count_id;

  -- A draft is still being counted. Nothing to explain, nothing to record.
  if parent_status is distinct from 'submitted' then
    return new;
  end if;

  -- Only a change to the figure itself needs justifying. Re-saving the same
  -- number is not a correction, and demanding a reason for it would train people
  -- to type one in automatically.
  if new.packs is not distinct from old.packs then
    return new;
  end if;

  if coalesce(btrim(new.corrected_by), '') = '' then
    raise exception
      'Correcting a submitted count needs the name of whoever is correcting it.'
      using errcode = 'check_violation';
  end if;
  if length(coalesce(btrim(new.corrected_reason), '')) < 3 then
    raise exception
      'Correcting a submitted count needs a reason — it restates that day''s variance '
      'and the next day''s opening, and somebody will ask why.'
      using errcode = 'check_violation';
  end if;

  new.corrected_by     := btrim(new.corrected_by);
  new.corrected_reason := btrim(new.corrected_reason);
  new.corrected_at     := now();

  insert into stock_count_correction
    (count_id, product_id, old_packs, new_packs, reason, corrected_by)
  values
    (old.count_id, old.product_id, old.packs, new.packs,
     new.corrected_reason, new.corrected_by);

  return new;
end $$;

drop trigger if exists stock_count_line_correct on stock_count_line;
create trigger stock_count_line_correct
  before update on stock_count_line
  for each row execute function stock_count_line_correct();

-- ------------------------------------------------------------
-- 4. Policies
-- ------------------------------------------------------------
alter table stock_count_correction enable row level security;

drop policy if exists read_correction on stock_count_correction;
create policy read_correction on stock_count_correction
  for select to anon, authenticated using (true);

-- Deliberately NO insert, update or delete policy. The trigger is SECURITY
-- DEFINER and so bypasses RLS; nothing else can put a row here or take one away.

-- The line update policy has to admit a submitted parent now. The freeze moves
-- from "you cannot change it" to "you cannot change it without saying who you
-- are and why", which the trigger enforces.
drop policy if exists update_line on stock_count_line;
create policy update_line on stock_count_line for update to anon, authenticated
  using (exists (select 1 from stock_count c
                  where c.count_id = stock_count_line.count_id
                    and c.status in ('draft', 'submitted')))
  with check (exists (select 1 from stock_count c
                       where c.count_id = stock_count_line.count_id
                         and c.status in ('draft', 'submitted'))
              and packs >= 0);

commit;

-- ------------------------------------------------------------
-- 5. Verify
-- ------------------------------------------------------------

-- The three new columns are on the line table.
select column_name, data_type, is_nullable
  from information_schema.columns
 where table_name = 'stock_count_line'
   and column_name in ('corrected_by', 'corrected_reason', 'corrected_at')
 order by column_name;

-- The trigger is attached.
select tgname, pg_get_triggerdef(oid)
  from pg_trigger
 where tgrelid = 'stock_count_line'::regclass and not tgisinternal;

-- One read policy on the audit table and nothing else.
select polname, polcmd, pg_get_expr(polqual, polrelid) as using_expr
  from pg_policy where polrelid = 'stock_count_correction'::regclass;

-- The line policy states both halves — the 05 trap.
select polname,
       pg_get_expr(polqual, polrelid)      as using_expr,
       pg_get_expr(polwithcheck, polrelid) as with_check
  from pg_policy
 where polrelid = 'stock_count_line'::regclass and polname = 'update_line';

-- ------------------------------------------------------------
-- What it looks like when it works (run against a real submitted count):
--
--   -- refused: no name, no reason
--   update stock_count_line set packs = 99
--    where count_id = 25 and product_id = '100740';
--   -- ERROR: Correcting a submitted count needs the name of whoever is correcting it.
--
--   -- accepted, and audited
--   update stock_count_line
--      set packs = 99, corrected_by = 'Rosa', corrected_reason = 'recounted, 99 on shelf'
--    where count_id = 25 and product_id = '100740';
--
--   select * from stock_count_correction where count_id = 25;
-- ------------------------------------------------------------
